version: '3.3'
services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SENTRY_DSN=${SENTRY_DSN}
      - VALID_API_KEYS=${VALID_API_KEYS}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS} 
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - TOGETHER_API_KEY=${TOGETHER_API_KEY}
      - LANGCHAIN_TRACING_V2=${LANGCHAIN_TRACING_V2}
      - LANGCHAIN_ENDPOINT=${LANGCHAIN_ENDPOINT}
      - LANGCHAIN_API_KEY=${LANGCHAIN_API_KEY}
      - LANGCHAIN_PROJECT=${LANGCHAIN_PROJECT}
    env_file:
      - .env      