version: '3.3'

services:
  # Main ChatRaghu backend service
  chatraghu-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      # Mounts the host's current directory into the container at /app
      # This enables live code reloading for the main backend service
      - ./:/app
    env_file:
      - .env
    environment:
      - EVALUATION_SERVICE_URL=http://evaluation-service:8001
      - EVALUATION_SERVICE_TIMEOUT=30
      - MOCK_EVAL_CLIENT=true
    depends_on:
      - evaluation-service
    networks:
      - chatraghu-network

  # Evaluation service
  evaluation-service:
    build:
      context: ./evals-service
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    volumes:
      # Mounts the host's evals-service directory into the container at /app
      # This enables live code reloading for the evaluation service
      - ./evals-service:/app
      # Persist evaluation results outside the container
      - ./evals-service/eval_results:/app/eval_results
      # Persist audit data outside the container
      - ./evals-service/audit_data:/app/audit_data
    env_file:
      - .env
    environment:
      - STORAGE_BATCH_SIZE=50
      - STORAGE_WRITE_TIMEOUT_SECONDS=300
    networks:
      - chatraghu-network

networks:
  chatraghu-network:
    driver: bridge
